spring:
  config:
    activate:
      on-profile: test
name: test-yaml
environment: testing
enabled: true
databaseDriver: com.mysql.cj.jdbc.Driver
databaseSource: jdbc:mysql://localhost:8085/cdb?useSSL=false
dbUser: root


