spring:
  config:
    activate:
      on-profile: test
name: test-yaml
environment: testing
enabled: true
databaseDriver: com.mysql.cj.jdbc.Driver
databaseSource: jdbc:mysql://chessdemondb.mysql.database.azure.com:3306/cdb?useSSL=false
dbUser: chessdemondb
dbPass: Norfolk15!

